/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherResultsRouteImport } from './routes/_authenticated/teacher/results'
import { Route as AuthenticatedTeacherAssignmentsRouteImport } from './routes/_authenticated/teacher/assignments'
import { Route as AuthenticatedParentDashboardRouteImport } from './routes/_authenticated/parent/dashboard'
import { Route as AuthenticatedParentChildrenRouteImport } from './routes/_authenticated/parent/children'
import { Route as AuthenticatedParentAssignmentsRouteImport } from './routes/_authenticated/parent/assignments'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin/classes'
import { Route as AuthenticatedAccountantFeesRouteImport } from './routes/_authenticated/accountant/fees'
import { Route as AuthenticatedParentStudentsStudentIdRouteImport } from './routes/_authenticated/parent/students.$studentId'
import { Route as AuthenticatedParentStudentsStudentIdAssignmentsRouteImport } from './routes/_authenticated/parent/students.$studentId.assignments'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherResultsRoute =
  AuthenticatedTeacherResultsRouteImport.update({
    id: '/teacher/results',
    path: '/teacher/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherAssignmentsRoute =
  AuthenticatedTeacherAssignmentsRouteImport.update({
    id: '/teacher/assignments',
    path: '/teacher/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentDashboardRoute =
  AuthenticatedParentDashboardRouteImport.update({
    id: '/parent/dashboard',
    path: '/parent/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentChildrenRoute =
  AuthenticatedParentChildrenRouteImport.update({
    id: '/parent/children',
    path: '/parent/children',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentAssignmentsRoute =
  AuthenticatedParentAssignmentsRouteImport.update({
    id: '/parent/assignments',
    path: '/parent/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/admin/classes',
    path: '/admin/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountantFeesRoute =
  AuthenticatedAccountantFeesRouteImport.update({
    id: '/accountant/fees',
    path: '/accountant/fees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentStudentsStudentIdRoute =
  AuthenticatedParentStudentsStudentIdRouteImport.update({
    id: '/parent/students/$studentId',
    path: '/parent/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentStudentsStudentIdAssignmentsRoute =
  AuthenticatedParentStudentsStudentIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedParentStudentsStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/accountant/fees': typeof AuthenticatedAccountantFeesRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/teacher/results': typeof AuthenticatedTeacherResultsRoute
  '/parent/students/$studentId': typeof AuthenticatedParentStudentsStudentIdRouteWithChildren
  '/parent/students/$studentId/assignments': typeof AuthenticatedParentStudentsStudentIdAssignmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/accountant/fees': typeof AuthenticatedAccountantFeesRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/teacher/results': typeof AuthenticatedTeacherResultsRoute
  '/parent/students/$studentId': typeof AuthenticatedParentStudentsStudentIdRouteWithChildren
  '/parent/students/$studentId/assignments': typeof AuthenticatedParentStudentsStudentIdAssignmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/accountant/fees': typeof AuthenticatedAccountantFeesRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/_authenticated/parent/children': typeof AuthenticatedParentChildrenRoute
  '/_authenticated/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/_authenticated/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/_authenticated/teacher/results': typeof AuthenticatedTeacherResultsRoute
  '/_authenticated/parent/students/$studentId': typeof AuthenticatedParentStudentsStudentIdRouteWithChildren
  '/_authenticated/parent/students/$studentId/assignments': typeof AuthenticatedParentStudentsStudentIdAssignmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/change-password'
    | '/login'
    | '/pending'
    | '/register'
    | '/accountant/fees'
    | '/admin/classes'
    | '/admin/students'
    | '/admin/users'
    | '/parent/assignments'
    | '/parent/children'
    | '/parent/dashboard'
    | '/teacher/assignments'
    | '/teacher/results'
    | '/parent/students/$studentId'
    | '/parent/students/$studentId/assignments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/change-password'
    | '/login'
    | '/pending'
    | '/register'
    | '/accountant/fees'
    | '/admin/classes'
    | '/admin/students'
    | '/admin/users'
    | '/parent/assignments'
    | '/parent/children'
    | '/parent/dashboard'
    | '/teacher/assignments'
    | '/teacher/results'
    | '/parent/students/$studentId'
    | '/parent/students/$studentId/assignments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/change-password'
    | '/login'
    | '/pending'
    | '/register'
    | '/_authenticated/accountant/fees'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/users'
    | '/_authenticated/parent/assignments'
    | '/_authenticated/parent/children'
    | '/_authenticated/parent/dashboard'
    | '/_authenticated/teacher/assignments'
    | '/_authenticated/teacher/results'
    | '/_authenticated/parent/students/$studentId'
    | '/_authenticated/parent/students/$studentId/assignments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/results': {
      id: '/_authenticated/teacher/results'
      path: '/teacher/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof AuthenticatedTeacherResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/assignments': {
      id: '/_authenticated/teacher/assignments'
      path: '/teacher/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof AuthenticatedTeacherAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/dashboard': {
      id: '/_authenticated/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof AuthenticatedParentDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/children': {
      id: '/_authenticated/parent/children'
      path: '/parent/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AuthenticatedParentChildrenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/assignments': {
      id: '/_authenticated/parent/assignments'
      path: '/parent/assignments'
      fullPath: '/parent/assignments'
      preLoaderRoute: typeof AuthenticatedParentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accountant/fees': {
      id: '/_authenticated/accountant/fees'
      path: '/accountant/fees'
      fullPath: '/accountant/fees'
      preLoaderRoute: typeof AuthenticatedAccountantFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/students/$studentId': {
      id: '/_authenticated/parent/students/$studentId'
      path: '/parent/students/$studentId'
      fullPath: '/parent/students/$studentId'
      preLoaderRoute: typeof AuthenticatedParentStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/students/$studentId/assignments': {
      id: '/_authenticated/parent/students/$studentId/assignments'
      path: '/assignments'
      fullPath: '/parent/students/$studentId/assignments'
      preLoaderRoute: typeof AuthenticatedParentStudentsStudentIdAssignmentsRouteImport
      parentRoute: typeof AuthenticatedParentStudentsStudentIdRoute
    }
  }
}

interface AuthenticatedParentStudentsStudentIdRouteChildren {
  AuthenticatedParentStudentsStudentIdAssignmentsRoute: typeof AuthenticatedParentStudentsStudentIdAssignmentsRoute
}

const AuthenticatedParentStudentsStudentIdRouteChildren: AuthenticatedParentStudentsStudentIdRouteChildren =
  {
    AuthenticatedParentStudentsStudentIdAssignmentsRoute:
      AuthenticatedParentStudentsStudentIdAssignmentsRoute,
  }

const AuthenticatedParentStudentsStudentIdRouteWithChildren =
  AuthenticatedParentStudentsStudentIdRoute._addFileChildren(
    AuthenticatedParentStudentsStudentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountantFeesRoute: typeof AuthenticatedAccountantFeesRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedParentAssignmentsRoute: typeof AuthenticatedParentAssignmentsRoute
  AuthenticatedParentChildrenRoute: typeof AuthenticatedParentChildrenRoute
  AuthenticatedParentDashboardRoute: typeof AuthenticatedParentDashboardRoute
  AuthenticatedTeacherAssignmentsRoute: typeof AuthenticatedTeacherAssignmentsRoute
  AuthenticatedTeacherResultsRoute: typeof AuthenticatedTeacherResultsRoute
  AuthenticatedParentStudentsStudentIdRoute: typeof AuthenticatedParentStudentsStudentIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountantFeesRoute: AuthenticatedAccountantFeesRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedParentAssignmentsRoute: AuthenticatedParentAssignmentsRoute,
  AuthenticatedParentChildrenRoute: AuthenticatedParentChildrenRoute,
  AuthenticatedParentDashboardRoute: AuthenticatedParentDashboardRoute,
  AuthenticatedTeacherAssignmentsRoute: AuthenticatedTeacherAssignmentsRoute,
  AuthenticatedTeacherResultsRoute: AuthenticatedTeacherResultsRoute,
  AuthenticatedParentStudentsStudentIdRoute:
    AuthenticatedParentStudentsStudentIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
